<a href="https://colab.research.google.com/github/xcl-esc/Analise_Airbnb/blob/main/Limpeza_e_Manipulacao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

-**Configurando caminhos e conectando ao Drive**

Essa primeira vista serve pra limpar os dados,e testar comandos de visualização dos dados.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
cd /content/drive/MyDrive/analise_de_dados/Testes

/content/drive/MyDrive/analise_de_dados/Testes

In [ ]:
#---------------------------#
##Bloco de notas:
#um bom insigt seria dizer os top 5 maiores custos beneficios de cada categoria
#e trazer um bom custo beneficio pra viajar sozinho e outro pra viajar em familia
# as variaveis pra isso serao: id e listing_url pra localizar o imovel,

**Imports de bibliotecas**

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('dados.csv')

Observando a estrutura de linhas e colunas do DF

In [ ]:
df.shape

(21286, 27)

Observando os 5 primeiros itens do dataframe para desenvolver insights.

In [ ]:
df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,host_id,host_name,host_since,...,bedrooms,beds,price,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
0,752318531145700331,https://www.airbnb.com/rooms/752318531145700331,20250624193519,2025-06-26,city scrape,Exceptional 2 Bed Copa 100m Beach,2 bedroom apartment 100 meters from Copacabana...,397106841,Jump In,2021-04-15,...,2.0,4.0,$507.00,3.00,5.00,4.00,2.00,3.00,5.00,3.00
1,1411843238290322081,https://www.airbnb.com/rooms/1411843238290322081,20250624193519,2025-06-27,city scrape,Tiny House Praia de Botafogo,welcome to your Apto in Botafogo!<br /><br />G...,156783825,Morada,2017-10-30,...,1.0,1.0,$215.00,4.82,4.91,4.91,5.00,4.91,5.00,4.82
2,1339188406746847719,https://www.airbnb.com/rooms/1339188406746847719,20250624193519,2025-06-27,city scrape,apartamento D Cs K,"Relax with the whole family, or with friends ...",674375308,Deisiana,2025-01-21,...,2.0,4.0,$90.00,5.00,5.00,5.00,5.00,5.00,4.80,5.00
3,1050604592912820183,https://www.airbnb.com/rooms/1050604592912820183,20250624193519,2025-06-28,city scrape,Renovated and charming close to Leblon beach!,"Apartment completely renovated, modern, super ...",508835814,Rio To Stay,2023-04-06,...,2.0,3.0,$769.00,4.75,4.88,4.84,4.88,4.94,4.88,4.69
4,1349515326730602111,https://www.airbnb.com/rooms/1349515326730602111,20250624193519,2025-06-26,city scrape,Ipanema_Errejota,This cozy 1 bedroom apartment located in the h...,198908935,FlÃ¡vio,2018-06-29,...,1.0,2.0,$351.00,4.82,4.82,4.91,4.82,5.00,4.73,4.73

Observações:

In [ ]:
df.tail(5)

,id,listing_url,scrape_id,last_scraped,source,name,description,host_id,host_name,host_since,...,bedrooms,beds,price,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
21281,1223140834392925320,https://www.airbnb.com/rooms/1223140834392925320,20250624193519,2025-06-26,city scrape,Quarto Corcovado MarocaRIO,"Welcome to the Corcovado Room, one of our fine...",139136788,Marcio,2017-07-07,...,1.0,1.0,$331.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21282,1446320012960368175,https://www.airbnb.com/rooms/1446320012960368175,20250624193519,2025-06-27,city scrape,Entre praias Ipanema Copacabana,"Cozy apartment between Copacabana and Ipanema,...",664003524,JoÃ£o Pedro,2024-11-25,...,1.0,2.0,$350.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21283,1076007360937301736,https://www.airbnb.com/rooms/1076007360937301736,20250624193519,2025-06-27,city scrape,Copanema - Apartamento charmoso a 5 min da praia,"Super charming and cozy apartment, just a few ...",449853878,Bruno,2022-03-16,...,1.0,2.0,$489.00,5.00,5.00,5.00,5.00,5.0,5.00,4.67
21284,1400835747819798620,https://www.airbnb.com/rooms/1400835747819798620,20250624193519,2025-06-26,city scrape,suite em Copacabana com cozinha e lavanderia,Take a break to relax in this serene oasis.,106226420,Jose ClÃ¡udio,2016-12-05,...,1.0,2.0,$140.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21285,27428250,https://www.airbnb.com/rooms/27428250,20250624193519,2025-06-26,city scrape,Casa inteira com piscina - Casa Insanta,This listing refers to the rental of the entir...,193205371,Victor,2018-06-03,...,6.0,16.0,"$2,697.00",4.85,4.77,4.46,4.92,5.0,4.92,4.77

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21286 entries, 0 to 21285
Data columns (total 27 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           21286 non-null  int64
 1   listing_url                  21286 non-null  object
 2   scrape_id                    21286 non-null  int64
 3   last_scraped                 21286 non-null  object
 4   source                       21286 non-null  object
 5   name                         21286 non-null  object
 6   description                  20766 non-null  object
 7   host_id                      21286 non-null  int64
 8   host_name                    20534 non-null  object
 9   host_since                   20495 non-null  object
 10  neighbourhood                8320 non-null   object
 11  neighbourhood_cleansed       21286 non-null  object
 12  latitude                     21286 non-null  object
 13  longitude                    21286 non-null  object
 14  room_type                    21286 non-null  object
 15  accommodates                 21286 non-null  int64
 16  bathrooms                    19465 non-null  float64
 17  bedrooms                     20919 non-null  float64
 18  beds                         19480 non-null  float64
 19  price                        19486 non-null  object
 20  review_scores_rating         16919 non-null  float64
 21  review_scores_accuracy       16914 non-null  float64
 22  review_scores_cleanliness    16915 non-null  float64
 23  review_scores_checkin        16915 non-null  float64
 24  review_scores_communication  16914 non-null  float64
 25  review_scores_location       16914 non-null  float64
 26  review_scores_value          16914 non-null  float64
dtypes: float64(10), int64(4), object(13)
memory usage: 4.4+ MB

Início da limpeza dos dados<br></br>
Importante observar que review_scores_rating e review_scores_accuracy sao respectivamente a avaliação e a precisão do que foi dito no imóvel, se tinha o que o anuncio afirmafva

In [ ]:
df['rating_vs_accuracy'] = df['review_scores_rating'] == df['review_scores_accuracy']
print(df)

                        id                                       listing_url  \
0       752318531145700331   https://www.airbnb.com/rooms/752318531145700331
1      1411843238290322081  https://www.airbnb.com/rooms/1411843238290322081
2      1339188406746847719  https://www.airbnb.com/rooms/1339188406746847719
3      1050604592912820183  https://www.airbnb.com/rooms/1050604592912820183
4      1349515326730602111  https://www.airbnb.com/rooms/1349515326730602111
...                    ...                                               ...
21281  1223140834392925320  https://www.airbnb.com/rooms/1223140834392925320
21282  1446320012960368175  https://www.airbnb.com/rooms/1446320012960368175
21283  1076007360937301736  https://www.airbnb.com/rooms/1076007360937301736
21284  1400835747819798620  https://www.airbnb.com/rooms/1400835747819798620
21285             27428250             https://www.airbnb.com/rooms/27428250

            scrape_id last_scraped       source  \
0      20250624193519   2025-06-26  city scrape
1      20250624193519   2025-06-27  city scrape
2      20250624193519   2025-06-27  city scrape
3      20250624193519   2025-06-28  city scrape
4      20250624193519   2025-06-26  city scrape
...               ...          ...          ...
21281  20250624193519   2025-06-26  city scrape
21282  20250624193519   2025-06-27  city scrape
21283  20250624193519   2025-06-27  city scrape
21284  20250624193519   2025-06-26  city scrape
21285  20250624193519   2025-06-26  city scrape

                                                   name  \
0                     Exceptional 2 Bed Copa 100m Beach
1                          Tiny House Praia de Botafogo
2                                    apartamento D Cs K
3         Renovated and charming close to Leblon beach!
4                                      Ipanema_Errejota
...                                                 ...
21281                        Quarto Corcovado MarocaRIO
21282                   Entre praias Ipanema Copacabana
21283  Copanema - Apartamento charmoso a 5 min da praia
21284     suite em Copacabana com cozinha e  lavanderia
21285           Casa inteira com piscina - Casa Insanta

                                             description    host_id  \
0      2 bedroom apartment 100 meters from Copacabana...  397106841
1      welcome to your Apto in Botafogo!<br /><br />G...  156783825
2      Relax with the whole family, or with friends  ...  674375308
3      Apartment completely renovated, modern, super ...  508835814
4      This cozy 1 bedroom apartment located in the h...  198908935
...                                                  ...        ...
21281  Welcome to the Corcovado Room, one of our fine...  139136788
21282  Cozy apartment between Copacabana and Ipanema,...  664003524
21283  Super charming and cozy apartment, just a few ...  449853878
21284        Take a break to relax in this serene oasis.  106226420
21285  This listing refers to the rental of the entir...  193205371

           host_name  host_since  ...  beds      price review_scores_rating  \
0            Jump In  2021-04-15  ...   4.0    $507.00                 3.00
1             Morada  2017-10-30  ...   1.0    $215.00                 4.82
2           Deisiana  2025-01-21  ...   4.0     $90.00                 5.00
3        Rio To Stay  2023-04-06  ...   3.0    $769.00                 4.75
4            FlÃ¡vio  2018-06-29  ...   2.0    $351.00                 4.82
...              ...         ...  ...   ...        ...                  ...
21281         Marcio  2017-07-07  ...   1.0    $331.00                  NaN
21282    JoÃ£o Pedro  2024-11-25  ...   2.0    $350.00                  NaN
21283          Bruno  2022-03-16  ...   2.0    $489.00                 5.00
21284  Jose ClÃ¡udio  2016-12-05  ...   2.0    $140.00                  NaN
21285         Victor  2018-06-03  ...  16.0  $2,697.00                 4.85

      review_scores_accuracy review_scores_cleanliness  review_scores_checkin  \
0                       5.00                      4.00                   2.00
1                       4.91                      4.91                   5.00
2                       5.00                      5.00                   5.00
3                       4.88                      4.84                   4.88
4                       4.82                      4.91                   4.82
...                      ...                       ...                    ...
21281                    NaN                       NaN                    NaN
21282                    NaN                       NaN                    NaN
21283                   5.00                      5.00                   5.00
21284                    NaN                       NaN                    NaN
21285                   4.77                      4.46                   4.92

       review_scores_communication  review_scores_location  \
0                             3.00                    5.00
1                             4.91                    5.00
2                             5.00                    4.80
3                             4.94                    4.88
4                             5.00                    4.73
...                            ...                     ...
21281                          NaN                     NaN
21282                          NaN                     NaN
21283                         5.00                    5.00
21284                          NaN                     NaN
21285                         5.00                    4.92

       review_scores_value rating_vs_accuracy
0                     3.00              False
1                     4.82              False
2                     5.00               True
3                     4.69              False
4                     4.73               True
...                    ...                ...
21281                  NaN              False
21282                  NaN              False
21283                 4.67               True
21284                  NaN              False
21285                 4.77              False

[21286 rows x 28 columns]

In [ ]:
lista_de_colunas = list(df.columns)
print(lista_de_colunas)

['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name', 'description', 'host_id', 'host_name', 'host_since', 'neighbourhood', 'neighbourhood_cleansed', 'latitude', 'longitude', 'room_type', 'accommodates', 'bathrooms', 'bedrooms', 'beds', 'price', 'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 'review_scores_value', 'rating_vs_accuracy']

In [ ]:
dados_limpos = df.loc [:,  ['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'description',
                            'host_since', 'latitude', 'longitude', 'room_type', 'accommodates', 'bathrooms',
                            'bedrooms', 'beds', 'price', 'review_scores_rating', 'review_scores_accuracy']]
dados_limpos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21286 entries, 0 to 21285
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      21286 non-null  int64
 1   listing_url             21286 non-null  object
 2   scrape_id               21286 non-null  int64
 3   last_scraped            21286 non-null  object
 4   name                    21286 non-null  object
 5   description             20766 non-null  object
 6   host_since              20495 non-null  object
 7   latitude                21286 non-null  object
 8   longitude               21286 non-null  object
 9   room_type               21286 non-null  object
 10  accommodates            21286 non-null  int64
 11  bathrooms               19465 non-null  float64
 12  bedrooms                20919 non-null  float64
 13  beds                    19480 non-null  float64
 14  price                   19486 non-null  object
 15  review_scores_rating    16919 non-null  float64
 16  review_scores_accuracy  16914 non-null  float64
dtypes: float64(5), int64(3), object(9)
memory usage: 2.8+ MB

In [ ]:
dados_limpos.head()

,id,listing_url,scrape_id,last_scraped,name,description,host_since,latitude,longitude,room_type,accommodates,bathrooms,bedrooms,beds,price,review_scores_rating,review_scores_accuracy
0,752318531145700331,https://www.airbnb.com/rooms/752318531145700331,20250624193519,2025-06-26,Exceptional 2 Bed Copa 100m Beach,2 bedroom apartment 100 meters from Copacabana...,2021-04-15,"-22,96635","-43,17938",Entire home/apt,5,1.0,2.0,4.0,$507.00,3.00,5.00
1,1411843238290322081,https://www.airbnb.com/rooms/1411843238290322081,20250624193519,2025-06-27,Tiny House Praia de Botafogo,welcome to your Apto in Botafogo!<br /><br />G...,2017-10-30,"-22,94533","-43,18163",Entire home/apt,2,1.0,1.0,1.0,$215.00,4.82,4.91
2,1339188406746847719,https://www.airbnb.com/rooms/1339188406746847719,20250624193519,2025-06-27,apartamento D Cs K,"Relax with the whole family, or with friends ...",2025-01-21,"-22,9372198","-43,6966461",Entire home/apt,4,1.0,2.0,4.0,$90.00,5.00,5.00
3,1050604592912820183,https://www.airbnb.com/rooms/1050604592912820183,20250624193519,2025-06-28,Renovated and charming close to Leblon beach!,"Apartment completely renovated, modern, super ...",2023-04-06,"-22,981651797126293","-43,22314382772875",Entire home/apt,5,2.0,2.0,3.0,$769.00,4.75,4.88
4,1349515326730602111,https://www.airbnb.com/rooms/1349515326730602111,20250624193519,2025-06-26,Ipanema_Errejota,This cozy 1 bedroom apartment located in the h...,2018-06-29,"-22,983108","-43,2026608",Entire home/apt,4,1.5,1.0,2.0,$351.00,4.82,4.82

falta limpar o resto

In [ ]:
dados_limpos['room_type'].unique()

array(['Entire home/apt', 'Private room', 'Shared room', 'Hotel room'],
      dtype=object)

In [ ]:
dados_limpos['price'].unique()

array(['$507.00', '$215.00', '$90.00', ..., '$849.00', '$9,947.00',
       '$2,697.00'], dtype=object)

In [ ]:
dados_limpos['bathrooms'].unique()
dados_limpos['bedrooms'].unique()

array([ 2.,  1., nan,  4.,  3.,  0.,  6.,  5., 10.,  7.,  9.,  8., 13.,
       16., 11., 26., 27., 14., 12.])

Há 4 tipos de imóveis:
['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']
<br></br>
E em price, vejo 3 problemas:
cifrão, casas decimais separadas por vírgula e a tipagem como objeto(texto)
'$2,697.00', dtype=object
<br></br>
Já em banheiros e quartos, os dados estão tipados em float. E por curiosidade lavabos sao considerados como 0.5 no número de banheiros.
Também há valores nulos em muitas variáveis.

In [ ]:
#Primeiro limpamos a variável price
dados_limpos['price'] = dados_limpos['price'].str.replace('$', '')
dados_limpos['price'] = dados_limpos['price'].str.replace(',', '')
dados_limpos['price'].unique()

array(['507.00', '215.00', '90.00', ..., '849.00', '9947.00', '2697.00'],
      dtype=object)

In [ ]:
#Agora convertemos para a tipagem correta
dados_limpos['price'] = dados_limpos['price'].astype(float)
dados_limpos['price'].unique()

array([ 507.,  215.,   90., ...,  849., 9947., 2697.])

In [ ]:
dados_limpos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21286 entries, 0 to 21285
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      21286 non-null  int64
 1   listing_url             21286 non-null  object
 2   scrape_id               21286 non-null  int64
 3   last_scraped            21286 non-null  object
 4   name                    21286 non-null  object
 5   description             20766 non-null  object
 6   host_since              20495 non-null  object
 7   latitude                21286 non-null  object
 8   longitude               21286 non-null  object
 9   room_type               21286 non-null  object
 10  accommodates            21286 non-null  int64
 11  bathrooms               19465 non-null  float64
 12  bedrooms                20919 non-null  float64
 13  beds                    19480 non-null  float64
 14  price                   19486 non-null  float64
 15  review_scores_rating    16919 non-null  float64
 16  review_scores_accuracy  16914 non-null  float64
dtypes: float64(6), int64(3), object(8)
memory usage: 2.8+ MB

In [ ]:
(dados_limpos.isnull().sum() / len(dados_limpos)) * 100

id                         0.000000
listing_url                0.000000
scrape_id                  0.000000
last_scraped               0.000000
name                       0.000000
description                2.442920
host_since                 3.716058
latitude                   0.000000
longitude                  0.000000
room_type                  0.000000
accommodates               0.000000
bathrooms                  8.554919
bedrooms                   1.724138
beds                       8.484450
price                      8.456262
review_scores_rating      20.515832
review_scores_accuracy    20.539322
dtype: float64

Quando os dados nulos forem menores que 10% da base podem ser apagados, mas apra apagar deve haver um motivo. Para análise descritiva e estatística básica não há necessidade de apagar, mas para ML e clusterização geralmente as bibliotecas já vem prontas para lidar com os nulos apagando/ignorando ou será preciso apagá-los manualmente.

A limpeza dos nulos será feita apenas em price, bathrooms, bedrooms e beds. Já que: reviews, host_since e description não serão relevantes ter nulos ou não.

In [ ]:
dados_limpos = dados_limpos.dropna(subset=['price', 'bathrooms', 'bedrooms', 'beds'])
dados_limpos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19427 entries, 0 to 21285
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      19427 non-null  int64
 1   listing_url             19427 non-null  object
 2   scrape_id               19427 non-null  int64
 3   last_scraped            19427 non-null  object
 4   name                    19427 non-null  object
 5   description             18971 non-null  object
 6   host_since              18700 non-null  object
 7   latitude                19427 non-null  object
 8   longitude               19427 non-null  object
 9   room_type               19427 non-null  object
 10  accommodates            19427 non-null  int64
 11  bathrooms               19427 non-null  float64
 12  bedrooms                19427 non-null  float64
 13  beds                    19427 non-null  float64
 14  price                   19427 non-null  float64
 15  review_scores_rating    15569 non-null  float64
 16  review_scores_accuracy  15564 non-null  float64
dtypes: float64(6), int64(3), object(8)
memory usage: 2.7+ MB

In [ ]:
#Salvar csv para posteridade
dados_limpos.to_csv("dados_limpos.csv", index=False)