<a href="https://colab.research.google.com/github/xcl-esc/Analise_Airbnb/blob/main/Outros_codigos/Limpeza_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Essa primeira vista serve pra limpar os dados e testar alguns comandos de visualização dos dados.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
cd /content/drive/MyDrive/Analise_hotmart/Coleta_e_Limpeza/

/content/drive/MyDrive/Analise_hotmart/Coleta_e_Limpeza

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('dados_concatenados.csv')
df.info()

/tmp/ipykernel_7252/3451027075.py:1: DtypeWarning: Columns (9,18,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,38,39,40,41,43,46,49,58,62,68,76) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('dados_concatenados.csv')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86136 entries, 0 to 86135
Data columns (total 80 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            86136 non-null  int64
 1   name                                          86136 non-null  object
 2   host_id                                       86136 non-null  int64
 3   host_name                                     86114 non-null  object
 4   neighbourhood_group                           0 non-null      float64
 5   neighbourhood                                 59398 non-null  object
 6   latitude                                      86136 non-null  float64
 7   longitude                                     86136 non-null  float64
 8   room_type                                     86136 non-null  object
 9   price                                         77340 non-null  object
 10  minimum_nights                                86136 non-null  int64
 11  number_of_reviews                             86136 non-null  int64
 12  last_review                                   67764 non-null  object
 13  reviews_per_month                             67764 non-null  float64
 14  calculated_host_listings_count                86136 non-null  int64
 15  availability_365                              86136 non-null  int64
 16  number_of_reviews_ltm                         86136 non-null  int64
 17  license                                       0 non-null      float64
 18  listing_url                                   43068 non-null  object
 19  scrape_id                                     43068 non-null  float64
 20  last_scraped                                  43068 non-null  object
 21  source                                        43068 non-null  object
 22  description                                   42017 non-null  object
 23  neighborhood_overview                         16330 non-null  object
 24  picture_url                                   43068 non-null  object
 25  host_url                                      43068 non-null  object
 26  host_since                                    43057 non-null  object
 27  host_location                                 34195 non-null  object
 28  host_about                                    20604 non-null  object
 29  host_response_time                            35890 non-null  object
 30  host_response_rate                            35890 non-null  object
 31  host_acceptance_rate                          39327 non-null  object
 32  host_is_superhost                             41613 non-null  object
 33  host_thumbnail_url                            43057 non-null  object
 34  host_picture_url                              43057 non-null  object
 35  host_neighbourhood                            37984 non-null  object
 36  host_listings_count                           43057 non-null  float64
 37  host_total_listings_count                     43057 non-null  float64
 38  host_verifications                            43057 non-null  object
 39  host_has_profile_pic                          43057 non-null  object
 40  host_identity_verified                        43057 non-null  object
 41  neighbourhood_cleansed                        43068 non-null  object
 42  neighbourhood_group_cleansed                  0 non-null      float64
 43  property_type                                 43068 non-null  object
 44  accommodates                                  43068 non-null  float64
 45  bathrooms                                     38635 non-null  float64
 46  bathrooms_text                                43015 non-null  object
 47  bedrooms                                      42096 non-null  float64
 48  beds                                          38660 non-null  float64
 49  amenities                                     43068 non-null  object
 50  maximum_nights                                43068 non-null  float64
 51  minimum_minimum_nights                        43064 non-null  float64
 52  maximum_minimum_nights                        43064 non-null  float64
 53  minimum_maximum_nights                        43064 non-null  float64
 54  maximum_maximum_nights                        43064 non-null  float64
 55  minimum_nights_avg_ntm                        43068 non-null  float64
 56  maximum_nights_avg_ntm                        43068 non-null  float64
 57  calendar_updated                              0 non-null      float64
 58  has_availability                              42115 non-null  object
 59  availability_30                               43068 non-null  float64
 60  availability_60                               43068 non-null  float64
 61  availability_90                               43068 non-null  float64
 62  calendar_last_scraped                         43068 non-null  object
 63  number_of_reviews_l30d                        43068 non-null  float64
 64  availability_eoy                              43068 non-null  float64
 65  number_of_reviews_ly                          43068 non-null  float64
 66  estimated_occupancy_l365d                     43068 non-null  float64
 67  estimated_revenue_l365d                       38670 non-null  float64
 68  first_review                                  33882 non-null  object
 69  review_scores_rating                          33882 non-null  float64
 70  review_scores_accuracy                        33881 non-null  float64
 71  review_scores_cleanliness                     33882 non-null  float64
 72  review_scores_checkin                         33881 non-null  float64
 73  review_scores_communication                   33881 non-null  float64
 74  review_scores_location                        33881 non-null  float64
 75  review_scores_value                           33880 non-null  float64
 76  instant_bookable                              43068 non-null  object
 77  calculated_host_listings_count_entire_homes   43068 non-null  float64
 78  calculated_host_listings_count_private_rooms  43068 non-null  float64
 79  calculated_host_listings_count_shared_rooms   43068 non-null  float64
dtypes: float64(39), int64(7), object(34)
memory usage: 52.6+ MB

In [5]:
df = df.sample(5000)
df.shape

(5000, 80)

In [6]:
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,...,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
33459,1334234251552214882,Praia de Copacabana,542286355,Glaucia,NaN,Copacabana,-22.969880,-43.183090,Private room,416.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82927,1449488184499591981,Rocinha Rua 2,479626975,Maria Aparecida,NaN,NaN,-22.988604,-43.245623,Entire home/apt,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,f,1.0,0.0,0.0
24750,1106389456622802254,CasaBabilônia.,497558895,Natalia,NaN,Leme,-22.961267,-43.171085,Private room,143.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54849,51897296,Rio hotel residence,56777871,Claudio,NaN,NaN,-23.010610,-43.344470,Entire home/apt,$450.00,...,5.0,4.29,5.0,4.86,5.0,4.71,f,3.0,0.0,0.0
27501,1213132418216497641,Oh My God! | A Melhor Casa do Joá!,14315601,Aroldo,NaN,Joá,-23.008068,-43.288392,Entire home/apt,20000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.tail()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,...,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
24342,1085647645918382040,Sobrado em Vila fechada bem localizada,95055593,Daniel,NaN,Taquara,-22.925779,-43.368940,Entire home/apt,162.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53863,46564416,Casa aconchegante com vista para Pão de Açúcar,13919301,Beatriz,NaN,"Glória, Rio de Janeiro, Brazil",-22.921460,-43.183240,Entire home/apt,$364.00,...,4.88,5.00,5.00,5.00,4.88,4.63,f,1.0,1.0,0.0
43309,826655969736870764,"Barra Olímpica 4, Riocentro, Praias",309591724,Renato,NaN,NaN,-22.963309,-43.400948,Entire home/apt,$199.00,...,4.89,4.84,4.89,4.79,4.74,4.79,f,13.0,0.0,0.0
53005,42224040,Riou016 Moderno Apt 2QT Frente Mar Copacabana,14314998,Rio Unique,NaN,NaN,-22.975690,-43.189100,Entire home/apt,$890.00,...,4.88,4.88,4.92,4.71,5.00,4.67,f,38.0,0.0,0.0
6692,22357366,Flat com garagem próximo a Metro de Botafogo,163480716,Gerd,NaN,Botafogo,-22.953280,-43.182550,Entire home/apt,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Início da limpeza dos dados

  - Começo selecionando apenas as colunas de interesse

  - Após isso resolver os valores e tipagem na coluna 'price'

  - E em price, vejo 3 problemas: cifrão, casas decimais separadas por vírgula e a tipagem como objeto(texto) '$2,697.00', dtype=object

  - Também vou padronizar o conteúdo das variáveis de texto

  - Farei a conversão nas variáveis: host_since e last_scraped para um formato de data válido

  - Já em banheiros e quartos, os dados estão tipados em float. E por curiosidade lavabos sao considerados como 0.5 no número de banheiros.
  
  - Também há valores nulos em muitas variáveis, esses valores serão tratados pois para o teste das hipóteses, os dados precisam ser válidos.

  - Os dados das colunas latitude e longitude estão salvos como texto (object) e possuem vírgula como separador, então farei basicamente o mesmo procedimento que fiz em price. Tirando a vírgula e passando o formato em float para serem acessados pelo cluster posteriormente.

In [8]:
#Listando as colunas para facilitar a copiar as colunas que quero
lista_de_colunas = df.columns
print(lista_de_colunas)

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license', 'listing_url',
       'scrape_id', 'last_scraped', 'source', 'description',
       'neighborhood_overview', 'picture_url', 'host_url', 'host_since',
       'host_location', 'host_about', 'host_response_time',
       'host_response_rate', 'host_acceptance_rate', 'host_is_superhost',
       'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood',
       'host_listings_count', 'host_total_listings_count',
       'host_verifications', 'host_has_profile_pic', 'host_identity_verified',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed',
       'property_type', 'accommodates', 'bathrooms', 'bathrooms_text',
       'bedrooms', 'beds', 'amenities', 'maximum_nights',
       'minimum_minimum_nights', 'maximum_minimum_nights',
       'minimum_maximum_nights', 'maximum_maximum_nights',
       'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'calendar_updated',
       'has_availability', 'availability_30', 'availability_60',
       'availability_90', 'calendar_last_scraped', 'number_of_reviews_l30d',
       'availability_eoy', 'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'review_scores_rating',
       'review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_scores_communication',
       'review_scores_location', 'review_scores_value', 'instant_bookable',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms'],
      dtype='object')

In [9]:
dados_limpos = df.loc [:,  ['id', 'listing_url', 'scrape_id', 'last_scraped', 'name', 'description',
                            'host_since', 'neighbourhood_cleansed', 'latitude', 'longitude', 'room_type', 'accommodates', 'bathrooms',
                            'bedrooms', 'beds', 'price', 'review_scores_rating', 'review_scores_accuracy']]
dados_limpos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5000 entries, 33459 to 6692
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      5000 non-null   int64
 1   listing_url             2580 non-null   object
 2   scrape_id               2580 non-null   float64
 3   last_scraped            2580 non-null   object
 4   name                    5000 non-null   object
 5   description             2524 non-null   object
 6   host_since              2579 non-null   object
 7   neighbourhood_cleansed  2580 non-null   object
 8   latitude                5000 non-null   float64
 9   longitude               5000 non-null   float64
 10  room_type               5000 non-null   object
 11  accommodates            2580 non-null   float64
 12  bathrooms               2335 non-null   float64
 13  bedrooms                2512 non-null   float64
 14  beds                    2337 non-null   float64
 15  price                   4534 non-null   object
 16  review_scores_rating    2037 non-null   float64
 17  review_scores_accuracy  2037 non-null   float64
dtypes: float64(9), int64(1), object(8)
memory usage: 742.2+ KB

In [10]:
#Loop para a quantidade e tipos de dados da base
for coluna in dados_limpos.columns:
  print("==> ", coluna, " QTD únicos: ", dados_limpos[coluna].nunique())
  print(dados_limpos[coluna].unique())
  print()

==>  id  QTD únicos:  4843
[1334234251552214882 1449488184499591981 1106389456622802254 ...
  826655969736870764            42224040            22357366]

==>  listing_url  QTD únicos:  2580
[nan 'https://www.airbnb.com/rooms/1449488184499591981'
 'https://www.airbnb.com/rooms/51897296' ...
 'https://www.airbnb.com/rooms/46564416'
 'https://www.airbnb.com/rooms/826655969736870764'
 'https://www.airbnb.com/rooms/42224040']

==>  scrape_id  QTD únicos:  1
[           nan 2.02509262e+13]

==>  last_scraped  QTD únicos:  3
[nan '2025-09-28' '2025-09-26' '2025-09-27']

==>  name  QTD únicos:  4763
['Praia de Copacabana' 'Rocinha Rua 2' 'CasaBabilônia.' ...
 'Barra Olímpica 4,  Riocentro, Praias'
 'Riou016 Moderno Apt 2QT Frente Mar Copacabana'
 'Flat com garagem próximo a Metro de Botafogo']

==>  description  QTD únicos:  2407
[nan
 'Spacious and comfortable house, fully equipped for your stay. Located in Rocinha, Rua 2, with 1 bedroom with a double bed and a sofa bed in the living room, there is the possibility of requesting another mattress. With plenty of shops on the same street as the house. <br />NOTE: The street is not accessible by car. For this reason, there is no parking. <br />transportation by local vans and motorcycle taxi. Reference Point: Alex Market.<br />Mototaxi arrives at the main gate of the house.<br />Waiting for you with a delicious welcome snack.'
 '👋 One block from the beach, on Rua Domingos Ferreira, in Copacabana (Posto-4).<br /><br />This cozy living room and bedroom apartment is on the 12th floor of a family building, with only four apartments per floor. Located in the back, it receives the pleasant afternoon sun and offers a charming view of Christ the Redeemer. It has two air-conditioners, two bathrooms (social and en-suite) and a full kitchen with cooktop stove, microwave, refrigerator, pressurizer, gas heater and cabinets.'
 ...
 "Welcome!<br /><br />We will be happy to welcome you to our Rio de Janeiro retreat! You'll be a few meters from one of the most beautiful beaches in the Marvelous City, and we hope you'll enjoy every moment of this trip. <br /><br />Our house is based on love, respect, diversity and we will try to make your stay as enjoyable as possible! <br /><br />For guests who need to provide accounts for projects and companies, we provide a lease agreement for short periods."
 'House with a list view of Sugar Loaf and Guanabara Bay.<br />Corner to relax and listen to the birds, being still close to Largo dos Guimarães, a hottest point in Santa Teresa with the main bars and restaurants.'
 'You will have a great time in this comfortable place to stay with family and friends.<br />Total infrastructure: swimming pool, fitness center, restaurant, parking. Very close to the best white sand beaches. 10 minutes away.']

==>  host_since  QTD únicos:  1742
[nan '2022-09-15' '2016-01-30' ... '2012-12-17' '2014-04-05' '2019-11-14']

==>  neighbourhood_cleansed  QTD únicos:  97
[nan 'Rocinha' 'Barra da Tijuca' 'Copacabana' 'Catete' 'Ipanema' 'Centro'
 'Urca' 'Camorim' 'São Conrado' 'Botafogo' 'Leme' 'Maracanã' 'Leblon'
 'Jardim Botânico' 'Recreio dos Bandeirantes' 'Grajaú' 'Humaitá'
 'Santa Teresa' 'Alto da Boa Vista' 'Flamengo' 'Jacarepaguá' 'Laranjeiras'
 'Campo Grande' 'Rio Comprido' 'Santa Cruz' 'Vargem Grande' 'Glória' 'Joá'
 'Andaraí' 'Itanhangá' 'Gamboa' 'Méier' 'Barra de Guaratiba' 'Gávea'
 'Vidigal' 'Anil' 'Lagoa' 'Curicica' 'Cascadura' 'Vila Isabel' 'Tijuca'
 'Estácio' 'Praça Seca' 'Riachuelo' 'Freguesia (Jacarepaguá)'
 'Santo Cristo' 'Abolição' 'Jardim Guanabara' 'Cosme Velho' 'Bancários'
 'Guaratiba' 'Praia da Bandeira' 'Benfica' 'Cacuia' 'Sampaio'
 'Praça da Bandeira' 'São Cristóvão' 'Coelho Neto' 'Taquara' 'Paquetá'
 'Vargem Pequena' 'Piedade' 'Osvaldo Cruz' 'Pechincha' 'Realengo'
 'Catumbi' 'Manguinhos' 'Engenho de Dentro' 'Penha Circular'
 'Marechal Hermes' 'Jardim Carioca' 'Pavuna' 'Tanque' 'Senador Camará'
 'Campinho' 'Paciência' 'Encantado' 'Irajá' 'Vila Valqueire' 'Cidade Nova'
 'Ricardo de Albuquerque' 'Água Santa' 'Guadalupe' 'Jacaré' 'Ramos'
 'Bangu' 'Parque Anchieta' 'Cachambi' 'Gardênia Azul' 'Madureira'
 'Parada de Lucas' 'Portuguesa' 'Vila Militar' 'Engenho Novo' 'Inhaúma'
 'Saúde' 'Pedra de Guaratiba']

==>  latitude  QTD únicos:  4307
[-22.96988    -22.9886041  -22.9612673  ... -22.92577854 -22.96330911
 -22.97569   ]

==>  longitude  QTD únicos:  4359
[-43.18309    -43.2456234  -43.1710854  ... -43.18641867 -43.36893965
 -43.40094819]

==>  room_type  QTD únicos:  4
['Private room' 'Entire home/apt' 'Shared room' 'Hotel room']

==>  accommodates  QTD únicos:  16
[nan  3.  4.  6.  5.  2.  8. 12. 10.  9.  7.  1. 15. 16. 14. 13. 11.]

==>  bathrooms  QTD únicos:  17
[nan 2.  3.  1.  4.5 1.5 2.5 4.  6.  3.5 0.5 0.  5.5 5.  7.  6.5 8.  8.5]

==>  bedrooms  QTD únicos:  9
[nan  1.  2.  3.  5.  0.  4.  6.  7. 11.]

==>  beds  QTD únicos:  21
[nan  2.  3.  0.  1.  6.  7.  5.  8. 10.  4.  9. 11. 20. 17. 14. 15. 12.
 25. 16. 40. 50.]

==>  price  QTD únicos:  1718
[416.0 nan 143.0 ... 770.0 '$649.00' '$890.00']

==>  review_scores_rating  QTD únicos:  85
[ nan 4.86 5.   4.81 4.73 4.97 4.33 4.58 4.79 4.29 4.93 4.78 4.87 4.77
 4.91 4.88 4.95 4.94 4.83 4.92 3.8  4.99 4.72 4.84 4.65 4.69 4.   4.98
 3.   4.4  4.54 4.89 4.76 4.5  4.9  4.96 4.85 4.67 4.7  4.8  4.64 4.82
 4.56 4.71 2.   4.68 4.75 3.5  4.2  3.75 4.57 4.63 4.61 4.74 4.23 4.14
 3.67 4.66 4.25 4.6  3.41 4.47 4.43 1.   2.75 4.44 4.45 4.27 4.59 4.55
 4.53 4.42 4.17 4.31 4.52 2.5  4.1  4.49 4.36 3.88 4.38 4.62 4.22 4.37
 4.26 4.28]

==>  review_scores_accuracy  QTD únicos:  83
[ nan 5.   4.88 4.93 4.33 4.73 4.79 4.29 4.89 4.87 4.62 4.91 4.56 4.97
 4.92 4.98 4.2  4.82 4.69 4.84 4.78 4.94 4.86 4.9  4.95 4.75 2.   4.42
 4.8  4.17 4.81 4.83 4.   4.66 4.65 4.5  4.67 4.7  4.99 4.96 4.63 1.
 4.68 4.72 4.77 4.6  4.41 3.   4.71 4.74 4.76 4.59 4.46 4.43 4.61 3.5
 4.57 4.54 3.83 4.85 3.67 3.33 4.51 4.47 3.53 4.25 3.75 4.64 4.55 3.8
 4.45 4.53 4.38 4.52 4.07 4.31 4.13 4.3  4.44 4.58 4.22 4.4  4.06 4.37]

In [11]:
#Primeiro limpamos a variável price
dados_limpos['price'] = dados_limpos['price'].str.replace('$', '')
dados_limpos['price'] = dados_limpos['price'].str.replace(',', '')
dados_limpos['price'].unique()

array([nan, '450.00', '1084.00', '3040.00', '184.00', '315.00', '238.00',
       '130.00', '16929.00', '204.00', '187.00', '1500.00', '152.00',
       '736.00', '412.00', '250.00', '598.00', '648.00', '468.00',
       '541.00', '221.00', '790.00', '300.00', '191.00', '1143.00',
       '454.0', '454.00', '700.00', '4356.00', '373.00', '435.00',
       '350.0', '1350.00', '24140.00', '406.00', '805.00', '188.00',
       '289.00', '1005.00', '590.00', '214.00', '715.00', '100.00',
       '102.00', '855.00', '245.00', '986.00', '128.00', '261.00',
       '487.00', '153.00', '351.0', '143.00', '210.00', '354.00',
       '518.00', '330.00', '275.00', '865.00', '462.00', '593.00',
       '370.00', '5000.00', '642.00', '2000.00', '1300.00', '532.00',
       '2840.00', '600.00', '1318.00', '193.00', '515.00', '457.00',
       '160.00', '295.00', '256.00', '500.00', '344.00', '1900.00',
       '479.00', '493.00', '90.00', '339.00', '296.00', '343.00',
       '117.00', '480.00', '827.00', '274.00', '270.00', '523.00',
       '272.00', '4000.00', '1800.00', '411.00', '161.00', '175.00',
       '235.00', '1000.00', '260.00', '202.00', '14550.00', '1342.00',
       '1080.00', '1215.00', '415.00', '220.00', '18000.00', '3956.00',
       '20628.00', '2043.00', '538.00', '129.00', '662.00', '70.00',
       '206.0', '125.00', '407.00', '121.00', '338.00', '70.0', '484.00',
       '231.00', '614.00', '285.00', '439.00', '223.00', '155.0',
       '692.00', '473.0', '124.00', '204.0', '132.00', '123.00', '141.00',
       '237.00', '166.00', '1275.00', '1826.00', '288.00', '858.0',
       '451.00', '1842.00', '472.00', '268.00', '24550.00', '281.00',
       '77.00', '534.00', '170.00', '185.00', '216.00', '158.00',
       '404.00', '613.00', '198.00', '390.00', '292.00', '167.00',
       '495.00', '199.00', '209.00', '502.00', '512.00', '157.00',
       '250.0', '385.00', '772.00', '140.00', '360.00', '84.00', '95.00',
       '269.00', '742.00', '312.00', '724.00', '800.00', '336.00',
       '136.00', '597.00', '549.00', '189.00', '290.00', '556.00',
       '984.00', '809.00', '108.00', '350.00', '676.00', '144.00',
       '193.0', '585.00', '1819.00', '452.00', '72.00', '186.0', '314.00',
       '126.00', '179.00', '465.0', '714.00', '192.00', '952.00',
       '302.00', '510.00', '180.00', '148.00', '201.00', '189.0',
       '1725.0', '477.00', '8000.00', '380.00', '883.00', '171.00',
       '900.00', '879.00', '499.00', '255.00', '399.00', '10582.00',
       '303.00', '219.00', '369.00', '247.00', '240.00', '843.0',
       '695.00', '1362.0', '430.00', '142.00', '529.00', '280.00',
       '212.00', '1086.00', '227.00', '550.00', '1200.00', '78.00',
       '400.00', '63.00', '11412.00', '228.00', '1638.00', '176.00',
       '413.00', '109.00', '221.0', '200.00', '242.00', '383.00',
       '340.00', '750.00', '456.00', '154.00', '482.00', '332.00',
       '76.00', '765.00', '318.00', '215.00', '99.00', '970.00', '81.00',
       '2623.00', '485.00', '488.00', '162.00', '320.00', '944.00',
       '444.00', '360.0', '183.00', '282.00', '650.00', '386.00',
       '520.00', '536.00', '322.00', '414.00', '150.00', '251.00',
       '2588.00', '11695.00', '1484.00', '867.00', '175.0', '299.00',
       '616.00', '137.00', '194.0', '693.00', '1488.00', '864.00',
       '286.00', '319.00', '325.00', '465.00', '258.00', '265.00',
       '810.00', '186.00', '375.00', '353.00', '368.00', '316.00',
       '276.00', '815.00', '138.00', '323.0', '366.00', '80.00', '329.00',
       '630.00', '156.0', '213.00', '372.00', '163.00', '2615.00',
       '680.00', '763.00', '799.00', '323.00', '197.00', '218.00',
       '741.0', '425.00', '226.00', '266.00', '155.00', '230.00',
       '1482.00', '120.00', '190.00', '3816.00', '560.00', '249.00',
       '278.00', '1310.00', '156.00', '420.00', '122.00', '202.0',
       '301.00', '1534.00', '225.0', '1610.00', '1332.00', '151.00',
       '260.0', '309.00', '352.00', '405.00', '563.00', '522.00',
       '498.00', '195.00', '341.00', '165.00', '1167.00', '116.00',
       '429.00', '673.00', '283.0', '660.00', '478.00', '416.00',
       '1856.00', '1125.0', '862.00', '929.00', '246.00', '524.00',
       '87.00', '225.00', '57.00', '172.00', '675.00', '54.00', '236.00',
       '173.00', '135.00', '471.00', '965.0', '410.00', '271.00', '153.0',
       '9656.00', '609.00', '537.00', '1119.00', '1337.00', '55.00',
       '3773.00', '1771.00', '960.00', '326.00', '605.00', '713.00',
       '2385.00', '422.00', '677.00', '760.00', '149.00', '580.00',
       '190.0', '5715.00', '365.00', '1140.00', '2104.00', '345.00',
       '145.00', '169.00', '458.00', '720.00', '364.00', '251.0',
       '306.00', '181.00', '327.00', '217.00', '957.00', '134.00',
       '2804.00', '508.00', '2700.00', '567.00', '4560.00', '229.00',
       '972.00', '310.00', '114.00', '394.00', '546.00', '783.00',
       '476.00', '739.00', '291.00', '1400.00', '56.00', '434.00',
       '612.00', '147.00', '987.00', '812.00', '283.00', '119.00',
       '460.0', '625.00', '731.00', '274.0', '1936.00', '207.00',
       '1580.00', '334.00', '102.0', '85.00', '279.00', '252.00',
       '635.00', '603.0', '273.00', '115.00', '244.00', '174.00',
       '1008.00', '116.0', '1374.00', '1059.00', '79.00', '846.00',
       '699.00', '579.00', '679.00', '880.00', '909.00', '233.00',
       '176.0', '460.00', '112.00', '618.00', '224.00', '91.00',
       '1090.00', '1642.00', '352.0', '904.0', '643.00', '8900.00',
       '107.00', '203.00', '428.00', '483.00', '1560.00', '347.00',
       '1023.00', '357.00', '2444.00', '120.0', '665.00', '440.00',
       '234.00', '632.00', '267.00', '12520.00', '222.00', '417.0',
       '205.00', '9000.00', '1852.00', '241.00', '6246.00', '266.0',
       '191.0', '968.00', '410.0', '850.00', '164.00', '978.00', '254.00',
       '3732.00', '178.00', '177.00', '544.00', '492.00', '825.00',
       '481.00', '391.00', '1385.00', '206.00', '348.00', '671.00',
       '253.00', '1700.00', '4437.00', '513.0', '390.0', '910.00',
       '606.00', '998.00', '1639.00', '307.00', '2093.00', '4293.00',
       '374.00', '729.00', '182.00', '15223.00', '920.00', '331.00',
       '610.00', '257.00', '1927.00', '652.00', '281.0', '822.00',
       '1830.00', '378.00', '208.00', '564.00', '355.00', '293.00',
       '259.00', '2147.00', '198.0', '570.00', '470.00', '196.00',
       '194.00', '999.00', '133.0', '5465.00', '661.00', '646.00',
       '9025.00', '94.00', '626.00', '10000.00', '358.00', '455.00',
       '6320.00', '734.00', '683.00', '433.00', '1789.00', '547.00',
       '962.00', '916.00', '92.00', '396.00', '521.00', '566.00',
       '1074.00', '1850.00', '686.00', '448.00', '528.0', '408.00',
       '294.00', '565.00', '980.00', '990.00', '243.00', '96.00',
       '927.00', '139.00', '4354.00', '464.00', '504.00', '5965.00',
       '1020.00', '276.0', '447.00', '657.00', '840.00', '7834.00',
       '342.00', '1081.00', '645.00', '2876.00', '131.00', '4429.00',
       '437.0', '505.00', '154.0', '572.00', '453.00', '443.00', '886.00',
       '366.0', '445.00', '858.00', '781.00', '403.00', '5501.00',
       '284.00', '543.00', '1784.00', '4845.00', '918.00', '511.00',
       '211.00', '297.00', '328.00', '833.00', '704.0', '555.00',
       '1115.00', '417.00', '98.00', '627.00', '574.00', '1989.00',
       '1101.00', '2872.00', '804.00', '1317.00', '275.0', '578.00',
       '232.00', '805.0', '308.00', '248.00', '264.00', '1029.00',
       '1100.00', '2715.00', '729.0', '3800.00', '1539.00', '611.00',
       '243.0', '2038.00', '4500.00', '118.00', '2582.00', '716.00',
       '432.00', '104.00', '819.00', '587.00', '630.0', '2309.0',
       '446.00', '313.0', '572.0', '540.00', '1745.00', '4025.00',
       '246.0', '620.00', '3000.00', '466.00', '604.00', '371.00',
       '774.00', '69.00', '848.00', '1527.00', '1630.00', '65.00',
       '59.00', '311.00', '1407.00', '589.00', '93.00', '449.00', '611.0',
       '216.0', '239.00', '816.00', '378.0', '473.00', '1260.00', '185.0',
       '1106.00', '930.00', '463.00', '1033.00', '461.00', '298.00',
       '376.00', '784.00', '436.00', '3500.00', '442.00', '127.00',
       '513.00', '1589.00', '2650.00', '2300.00', '101.00', '397.00',
       '272.0', '261.0', '321.00', '277.0', '637.00', '878.00', '786.00',
       '359.00', '1205.00', '575.00', '947.00', '324.00', '77.0',
       '1012.00', '780.00', '168.00', '209.0', '110.00', '1105.00',
       '965.00', '2658.00', '1517.00', '3600.00', '533.00', '299.0',
       '892.00', '106.00', '1109.00', '634.00', '2125.00', '115.0',
       '841.00', '4933.00', '561.00', '236.0', '50.0', '320.0',
       '12500.00', '617.00', '6000.00', '1248.00', '938.00', '913.00',
       '7337.00', '262.00', '1072.00', '595.00', '690.00', '315.0',
       '264.0', '1252.00', '398.00', '750.0', '159.00', '333.00',
       '752.00', '146.00', '672.00', '733.00', '4278.00', '2470.00',
       '1436.00', '113.00', '363.00', '1197.00', '527.00', '882.00',
       '1247.00', '387.00', '302.0', '748.00', '633.00', '553.00',
       '133.00', '636.00', '379.00', '526.00', '670.00', '2031.00',
       '674.00', '305.00', '545.00', '203.0', '586.00', '689.00',
       '475.00', '592.00', '3220.00', '392.00', '1971.00', '759.0',
       '459.00', '1620.00', '392.0', '3570.00', '401.00', '293.0',
       '242.0', '2367.0', '601.00', '423.00', '271.0', '199.0', '437.00',
       '1278.00', '552.00', '277.00', '1523.00', '1858.00', '362.00',
       '197.0', '743.00', '351.00', '8100.00', '7000.00', '983.00',
       '1290.00', '1229.00', '300.0', '775.0', '74.00', '2500.00',
       '308.0', '1842.0', '4574.00', '1701.0', '1627.00', '1425.00',
       '615.00', '2400.00', '956.00', '2821.00', '395.00', '369.0',
       '559.00', '304.00', '409.00', '558.0', '10560.00', '147.0',
       '552.0', '710.00', '337.00', '1246.00', '3155.00', '1600.00',
       '547.0', '779.00', '2454.00', '888.00', '569.00', '782.00',
       '384.00', '37558.00', '103.00', '95.0', '382.00', '937.00',
       '964.0', '471.0', '2278.00', '2683.00', '891.00', '517.00',
       '110.0', '30980.00', '870.00', '5500.00', '335.00', '244.0',
       '507.00', '458.0', '1351.00', '109.0', '530.00', '427.00',
       '263.00', '725.00', '486.00', '313.00', '1156.00', '490.00',
       '950.00', '1170.00', '1149.00', '3056.00', '230.0', '948.00',
       '288.0', '1520.00', '419.00', '1363.00', '2236.00', '2415.00',
       '1632.00', '791.00', '1411.00', '558.00', '519.00', '346.00',
       '418.00', '649.00', '890.00'], dtype=object)

In [12]:
#Agora converto para a tipagem correta
dados_limpos['price'] = dados_limpos['price'].astype(float)
dados_limpos['price'].unique()

array([   nan,   450.,  1084.,  3040.,   184.,   315.,   238.,   130.,
       16929.,   204.,   187.,  1500.,   152.,   736.,   412.,   250.,
         598.,   648.,   468.,   541.,   221.,   790.,   300.,   191.,
        1143.,   454.,   700.,  4356.,   373.,   435.,   350.,  1350.,
       24140.,   406.,   805.,   188.,   289.,  1005.,   590.,   214.,
         715.,   100.,   102.,   855.,   245.,   986.,   128.,   261.,
         487.,   153.,   351.,   143.,   210.,   354.,   518.,   330.,
         275.,   865.,   462.,   593.,   370.,  5000.,   642.,  2000.,
        1300.,   532.,  2840.,   600.,  1318.,   193.,   515.,   457.,
         160.,   295.,   256.,   500.,   344.,  1900.,   479.,   493.,
          90.,   339.,   296.,   343.,   117.,   480.,   827.,   274.,
         270.,   523.,   272.,  4000.,  1800.,   411.,   161.,   175.,
         235.,  1000.,   260.,   202., 14550.,  1342.,  1080.,  1215.,
         415.,   220., 18000.,  3956., 20628.,  2043.,   538.,   129.,
         662.,    70.,   206.,   125.,   407.,   121.,   338.,   484.,
         231.,   614.,   285.,   439.,   223.,   155.,   692.,   473.,
         124.,   132.,   123.,   141.,   237.,   166.,  1275.,  1826.,
         288.,   858.,   451.,  1842.,   472.,   268., 24550.,   281.,
          77.,   534.,   170.,   185.,   216.,   158.,   404.,   613.,
         198.,   390.,   292.,   167.,   495.,   199.,   209.,   502.,
         512.,   157.,   385.,   772.,   140.,   360.,    84.,    95.,
         269.,   742.,   312.,   724.,   800.,   336.,   136.,   597.,
         549.,   189.,   290.,   556.,   984.,   809.,   108.,   676.,
         144.,   585.,  1819.,   452.,    72.,   186.,   314.,   126.,
         179.,   465.,   714.,   192.,   952.,   302.,   510.,   180.,
         148.,   201.,  1725.,   477.,  8000.,   380.,   883.,   171.,
         900.,   879.,   499.,   255.,   399., 10582.,   303.,   219.,
         369.,   247.,   240.,   843.,   695.,  1362.,   430.,   142.,
         529.,   280.,   212.,  1086.,   227.,   550.,  1200.,    78.,
         400.,    63., 11412.,   228.,  1638.,   176.,   413.,   109.,
         200.,   242.,   383.,   340.,   750.,   456.,   154.,   482.,
         332.,    76.,   765.,   318.,   215.,    99.,   970.,    81.,
        2623.,   485.,   488.,   162.,   320.,   944.,   444.,   183.,
         282.,   650.,   386.,   520.,   536.,   322.,   414.,   150.,
         251.,  2588., 11695.,  1484.,   867.,   299.,   616.,   137.,
         194.,   693.,  1488.,   864.,   286.,   319.,   325.,   258.,
         265.,   810.,   375.,   353.,   368.,   316.,   276.,   815.,
         138.,   323.,   366.,    80.,   329.,   630.,   156.,   213.,
         372.,   163.,  2615.,   680.,   763.,   799.,   197.,   218.,
         741.,   425.,   226.,   266.,   230.,  1482.,   120.,   190.,
        3816.,   560.,   249.,   278.,  1310.,   420.,   122.,   301.,
        1534.,   225.,  1610.,  1332.,   151.,   309.,   352.,   405.,
         563.,   522.,   498.,   195.,   341.,   165.,  1167.,   116.,
         429.,   673.,   283.,   660.,   478.,   416.,  1856.,  1125.,
         862.,   929.,   246.,   524.,    87.,    57.,   172.,   675.,
          54.,   236.,   173.,   135.,   471.,   965.,   410.,   271.,
        9656.,   609.,   537.,  1119.,  1337.,    55.,  3773.,  1771.,
         960.,   326.,   605.,   713.,  2385.,   422.,   677.,   760.,
         149.,   580.,  5715.,   365.,  1140.,  2104.,   345.,   145.,
         169.,   458.,   720.,   364.,   306.,   181.,   327.,   217.,
         957.,   134.,  2804.,   508.,  2700.,   567.,  4560.,   229.,
         972.,   310.,   114.,   394.,   546.,   783.,   476.,   739.,
         291.,  1400.,    56.,   434.,   612.,   147.,   987.,   812.,
         119.,   460.,   625.,   731.,  1936.,   207.,  1580.,   334.,
          85.,   279.,   252.,   635.,   603.,   273.,   115.,   244.,
         174.,  1008.,  1374.,  1059.,    79.,   846.,   699.,   579.,
         679.,   880.,   909.,   233.,   112.,   618.,   224.,    91.,
        1090.,  1642.,   904.,   643.,  8900.,   107.,   203.,   428.,
         483.,  1560.,   347.,  1023.,   357.,  2444.,   665.,   440.,
         234.,   632.,   267., 12520.,   222.,   417.,   205.,  9000.,
        1852.,   241.,  6246.,   968.,   850.,   164.,   978.,   254.,
        3732.,   178.,   177.,   544.,   492.,   825.,   481.,   391.,
        1385.,   348.,   671.,   253.,  1700.,  4437.,   513.,   910.,
         606.,   998.,  1639.,   307.,  2093.,  4293.,   374.,   729.,
         182., 15223.,   920.,   331.,   610.,   257.,  1927.,   652.,
         822.,  1830.,   378.,   208.,   564.,   355.,   293.,   259.,
        2147.,   570.,   470.,   196.,   999.,   133.,  5465.,   661.,
         646.,  9025.,    94.,   626., 10000.,   358.,   455.,  6320.,
         734.,   683.,   433.,  1789.,   547.,   962.,   916.,    92.,
         396.,   521.,   566.,  1074.,  1850.,   686.,   448.,   528.,
         408.,   294.,   565.,   980.,   990.,   243.,    96.,   927.,
         139.,  4354.,   464.,   504.,  5965.,  1020.,   447.,   657.,
         840.,  7834.,   342.,  1081.,   645.,  2876.,   131.,  4429.,
         437.,   505.,   572.,   453.,   443.,   886.,   445.,   781.,
         403.,  5501.,   284.,   543.,  1784.,  4845.,   918.,   511.,
         211.,   297.,   328.,   833.,   704.,   555.,  1115.,    98.,
         627.,   574.,  1989.,  1101.,  2872.,   804.,  1317.,   578.,
         232.,   308.,   248.,   264.,  1029.,  1100.,  2715.,  3800.,
        1539.,   611.,  2038.,  4500.,   118.,  2582.,   716.,   432.,
         104.,   819.,   587.,  2309.,   446.,   313.,   540.,  1745.,
        4025.,   620.,  3000.,   466.,   604.,   371.,   774.,    69.,
         848.,  1527.,  1630.,    65.,    59.,   311.,  1407.,   589.,
          93.,   449.,   239.,   816.,  1260.,  1106.,   930.,   463.,
        1033.,   461.,   298.,   376.,   784.,   436.,  3500.,   442.,
         127.,  1589.,  2650.,  2300.,   101.,   397.,   321.,   277.,
         637.,   878.,   786.,   359.,  1205.,   575.,   947.,   324.,
        1012.,   780.,   168.,   110.,  1105.,  2658.,  1517.,  3600.,
         533.,   892.,   106.,  1109.,   634.,  2125.,   841.,  4933.,
         561.,    50., 12500.,   617.,  6000.,  1248.,   938.,   913.,
        7337.,   262.,  1072.,   595.,   690.,  1252.,   398.,   159.,
         333.,   752.,   146.,   672.,   733.,  4278.,  2470.,  1436.,
         113.,   363.,  1197.,   527.,   882.,  1247.,   387.,   748.,
         633.,   553.,   636.,   379.,   526.,   670.,  2031.,   674.,
         305.,   545.,   586.,   689.,   475.,   592.,  3220.,   392.,
        1971.,   759.,   459.,  1620.,  3570.,   401.,  2367.,   601.,
         423.,  1278.,   552.,  1523.,  1858.,   362.,   743.,  8100.,
        7000.,   983.,  1290.,  1229.,   775.,    74.,  2500.,  4574.,
        1701.,  1627.,  1425.,   615.,  2400.,   956.,  2821.,   395.,
         559.,   304.,   409.,   558., 10560.,   710.,   337.,  1246.,
        3155.,  1600.,   779.,  2454.,   888.,   569.,   782.,   384.,
       37558.,   103.,   382.,   937.,   964.,  2278.,  2683.,   891.,
         517., 30980.,   870.,  5500.,   335.,   507.,  1351.,   530.,
         427.,   263.,   725.,   486.,  1156.,   490.,   950.,  1170.,
        1149.,  3056.,   948.,  1520.,   419.,  1363.,  2236.,  2415.,
        1632.,   791.,  1411.,   519.,   346.,   418.,   649.,   890.])

In [13]:
dados_limpos['name'] = dados_limpos['name'].str.upper()
dados_limpos['description'] = dados_limpos['description'].str.upper()
dados_limpos['neighbourhood_cleansed'] = dados_limpos['neighbourhood_cleansed'].str.upper()
dados_limpos['name'].unique()

array(['PRAIA DE COPACABANA', 'ROCINHA RUA 2', 'CASABABILÔNIA.', ...,
       'BARRA OLÍMPICA 4,  RIOCENTRO, PRAIAS',
       'RIOU016 MODERNO APT 2QT FRENTE MAR COPACABANA',
       'FLAT COM GARAGEM PRÓXIMO A METRO DE BOTAFOGO'], dtype=object)

In [14]:
dados_limpos['description'].unique()

array([nan,
       'SPACIOUS AND COMFORTABLE HOUSE, FULLY EQUIPPED FOR YOUR STAY. LOCATED IN ROCINHA, RUA 2, WITH 1 BEDROOM WITH A DOUBLE BED AND A SOFA BED IN THE LIVING ROOM, THERE IS THE POSSIBILITY OF REQUESTING ANOTHER MATTRESS. WITH PLENTY OF SHOPS ON THE SAME STREET AS THE HOUSE. <BR />NOTE: THE STREET IS NOT ACCESSIBLE BY CAR. FOR THIS REASON, THERE IS NO PARKING. <BR />TRANSPORTATION BY LOCAL VANS AND MOTORCYCLE TAXI. REFERENCE POINT: ALEX MARKET.<BR />MOTOTAXI ARRIVES AT THE MAIN GATE OF THE HOUSE.<BR />WAITING FOR YOU WITH A DELICIOUS WELCOME SNACK.',
       '👋 ONE BLOCK FROM THE BEACH, ON RUA DOMINGOS FERREIRA, IN COPACABANA (POSTO-4).<BR /><BR />THIS COZY LIVING ROOM AND BEDROOM APARTMENT IS ON THE 12TH FLOOR OF A FAMILY BUILDING, WITH ONLY FOUR APARTMENTS PER FLOOR. LOCATED IN THE BACK, IT RECEIVES THE PLEASANT AFTERNOON SUN AND OFFERS A CHARMING VIEW OF CHRIST THE REDEEMER. IT HAS TWO AIR-CONDITIONERS, TWO BATHROOMS (SOCIAL AND EN-SUITE) AND A FULL KITCHEN WITH COOKTOP STOVE, MICROWAVE, REFRIGERATOR, PRESSURIZER, GAS HEATER AND CABINETS.',
       ...,
       "WELCOME!<BR /><BR />WE WILL BE HAPPY TO WELCOME YOU TO OUR RIO DE JANEIRO RETREAT! YOU'LL BE A FEW METERS FROM ONE OF THE MOST BEAUTIFUL BEACHES IN THE MARVELOUS CITY, AND WE HOPE YOU'LL ENJOY EVERY MOMENT OF THIS TRIP. <BR /><BR />OUR HOUSE IS BASED ON LOVE, RESPECT, DIVERSITY AND WE WILL TRY TO MAKE YOUR STAY AS ENJOYABLE AS POSSIBLE! <BR /><BR />FOR GUESTS WHO NEED TO PROVIDE ACCOUNTS FOR PROJECTS AND COMPANIES, WE PROVIDE A LEASE AGREEMENT FOR SHORT PERIODS.",
       'HOUSE WITH A LIST VIEW OF SUGAR LOAF AND GUANABARA BAY.<BR />CORNER TO RELAX AND LISTEN TO THE BIRDS, BEING STILL CLOSE TO LARGO DOS GUIMARÃES, A HOTTEST POINT IN SANTA TERESA WITH THE MAIN BARS AND RESTAURANTS.',
       'YOU WILL HAVE A GREAT TIME IN THIS COMFORTABLE PLACE TO STAY WITH FAMILY AND FRIENDS.<BR />TOTAL INFRASTRUCTURE: SWIMMING POOL, FITNESS CENTER, RESTAURANT, PARKING. VERY CLOSE TO THE BEST WHITE SAND BEACHES. 10 MINUTES AWAY.'],
      dtype=object)

In [15]:
dados_limpos['neighbourhood_cleansed'].unique()

array([nan, 'ROCINHA', 'BARRA DA TIJUCA', 'COPACABANA', 'CATETE',
       'IPANEMA', 'CENTRO', 'URCA', 'CAMORIM', 'SÃO CONRADO', 'BOTAFOGO',
       'LEME', 'MARACANÃ', 'LEBLON', 'JARDIM BOTÂNICO',
       'RECREIO DOS BANDEIRANTES', 'GRAJAÚ', 'HUMAITÁ', 'SANTA TERESA',
       'ALTO DA BOA VISTA', 'FLAMENGO', 'JACAREPAGUÁ', 'LARANJEIRAS',
       'CAMPO GRANDE', 'RIO COMPRIDO', 'SANTA CRUZ', 'VARGEM GRANDE',
       'GLÓRIA', 'JOÁ', 'ANDARAÍ', 'ITANHANGÁ', 'GAMBOA', 'MÉIER',
       'BARRA DE GUARATIBA', 'GÁVEA', 'VIDIGAL', 'ANIL', 'LAGOA',
       'CURICICA', 'CASCADURA', 'VILA ISABEL', 'TIJUCA', 'ESTÁCIO',
       'PRAÇA SECA', 'RIACHUELO', 'FREGUESIA (JACAREPAGUÁ)',
       'SANTO CRISTO', 'ABOLIÇÃO', 'JARDIM GUANABARA', 'COSME VELHO',
       'BANCÁRIOS', 'GUARATIBA', 'PRAIA DA BANDEIRA', 'BENFICA', 'CACUIA',
       'SAMPAIO', 'PRAÇA DA BANDEIRA', 'SÃO CRISTÓVÃO', 'COELHO NETO',
       'TAQUARA', 'PAQUETÁ', 'VARGEM PEQUENA', 'PIEDADE', 'OSVALDO CRUZ',
       'PECHINCHA', 'REALENGO', 'CATUMBI', 'MANGUINHOS',
       'ENGENHO DE DENTRO', 'PENHA CIRCULAR', 'MARECHAL HERMES',
       'JARDIM CARIOCA', 'PAVUNA', 'TANQUE', 'SENADOR CAMARÁ', 'CAMPINHO',
       'PACIÊNCIA', 'ENCANTADO', 'IRAJÁ', 'VILA VALQUEIRE', 'CIDADE NOVA',
       'RICARDO DE ALBUQUERQUE', 'ÁGUA SANTA', 'GUADALUPE', 'JACARÉ',
       'RAMOS', 'BANGU', 'PARQUE ANCHIETA', 'CACHAMBI', 'GARDÊNIA AZUL',
       'MADUREIRA', 'PARADA DE LUCAS', 'PORTUGUESA', 'VILA MILITAR',
       'ENGENHO NOVO', 'INHAÚMA', 'SAÚDE', 'PEDRA DE GUARATIBA'],
      dtype=object)

In [16]:
dados_limpos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5000 entries, 33459 to 6692
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      5000 non-null   int64
 1   listing_url             2580 non-null   object
 2   scrape_id               2580 non-null   float64
 3   last_scraped            2580 non-null   object
 4   name                    5000 non-null   object
 5   description             2524 non-null   object
 6   host_since              2579 non-null   object
 7   neighbourhood_cleansed  2580 non-null   object
 8   latitude                5000 non-null   float64
 9   longitude               5000 non-null   float64
 10  room_type               5000 non-null   object
 11  accommodates            2580 non-null   float64
 12  bathrooms               2335 non-null   float64
 13  bedrooms                2512 non-null   float64
 14  beds                    2337 non-null   float64
 15  price                   2467 non-null   float64
 16  review_scores_rating    2037 non-null   float64
 17  review_scores_accuracy  2037 non-null   float64
dtypes: float64(10), int64(1), object(7)
memory usage: 742.2+ KB

In [17]:
dados_limpos.host_since = pd.to_datetime(dados_limpos.host_since, format='%Y-%m-%d')

In [18]:
dados_limpos.last_scraped = pd.to_datetime(dados_limpos.last_scraped, format='%Y-%m-%d')

In [19]:
dados_limpos.last_scraped.unique()

<DatetimeArray>
['NaT', '2025-09-28 00:00:00', '2025-09-26 00:00:00', '2025-09-27 00:00:00']
Length: 4, dtype: datetime64[ns]

Quando os dados nulos forem menores que 10% da base podem ser apagados, mas para apagar deve haver um motivo. Para análise descritiva e estatística básica não há necessidade de apagar, mas para ML e clusterização geralmente as bibliotecas já vem prontas para lidar com os nulos apagando/ignorando ou será preciso apagá-los manualmente.<br></br>
- A limpeza dos nulos será feita apenas em **price, bathrooms, bedrooms e beds**. Já que: reviews, host_since e description não serão relevantes ter nulos ou não.

Abaixo é possível ver a qauntodade de dados nulos em todo o df.

In [20]:
(dados_limpos.isnull().sum() / len(dados_limpos)) * 100

id                         0.00
listing_url               48.40
scrape_id                 48.40
last_scraped              48.40
name                       0.00
description               49.52
host_since                48.42
neighbourhood_cleansed    48.40
latitude                   0.00
longitude                  0.00
room_type                  0.00
accommodates              48.40
bathrooms                 53.30
bedrooms                  49.76
beds                      53.26
price                     50.66
review_scores_rating      59.26
review_scores_accuracy    59.26
dtype: float64

Quando os dados nulos forem menores que 10% da base podem ser apagados, mas para apagar deve haver um motivo. Para análise descritiva e estatística básica não há necessidade de apagar, mas para ML e clusterização geralmente as bibliotecas já vem prontas para lidar com os nulos apagando/ignorando ou será preciso apagá-los manualmente.<br></br>
- A limpeza dos nulos será feita apenas em **price, bathrooms, bedrooms e beds**. Já que: reviews, host_since e description não serão relevantes ter nulos ou não.

In [21]:
dados_limpos = dados_limpos.dropna(subset=['price', 'bathrooms', 'bedrooms', 'beds'])
dados_limpos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2327 entries, 54849 to 53005
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      2327 non-null   int64
 1   listing_url             2327 non-null   object
 2   scrape_id               2327 non-null   float64
 3   last_scraped            2327 non-null   datetime64[ns]
 4   name                    2327 non-null   object
 5   description             2278 non-null   object
 6   host_since              2326 non-null   datetime64[ns]
 7   neighbourhood_cleansed  2327 non-null   object
 8   latitude                2327 non-null   float64
 9   longitude               2327 non-null   float64
 10  room_type               2327 non-null   object
 11  accommodates            2327 non-null   float64
 12  bathrooms               2327 non-null   float64
 13  bedrooms                2327 non-null   float64
 14  beds                    2327 non-null   float64
 15  price                   2327 non-null   float64
 16  review_scores_rating    1845 non-null   float64
 17  review_scores_accuracy  1845 non-null   float64
dtypes: datetime64[ns](2), float64(10), int64(1), object(5)
memory usage: 345.4+ KB

In [22]:
dados_limpos['latitude'] = dados_limpos['latitude'].astype(str).str.replace(',', '.')
dados_limpos['longitude'] = dados_limpos['longitude'].astype(str).str.replace(',', '.')

dados_limpos['latitude'] = dados_limpos['latitude'].astype(float)
dados_limpos['longitude'] = dados_limpos['longitude'].astype(float)

In [23]:
dados_limpos[['latitude', 'longitude']]

        latitude  longitude
54849 -23.010610 -43.344470
56855 -22.973036 -43.186057
73474 -22.984520 -43.201030
55738 -22.912950 -43.181260
65553 -22.954104 -43.168059
...          ...        ...
82970 -22.968100 -43.183410
60206 -23.009230 -43.364940
53863 -22.921460 -43.183240
43309 -22.963309 -43.400948
53005 -22.975690 -43.189100

[2327 rows x 2 columns]

  - Importante observar que review_scores_rating e review_scores_accuracy são respectivamente a avaliação e a precisão do que foi dito no anúncio do imóvel, ou seja, se possuía o que o anúncio afirmava entregar.

  Abaixo comparo os dois para observar.

In [24]:
dados_limpos['rating_vs_accuracy'] = dados_limpos['review_scores_rating'] == dados_limpos['review_scores_accuracy']
print(dados_limpos)

                        id                                       listing_url  \
54849             51897296             https://www.airbnb.com/rooms/51897296
56855   602842954033417083   https://www.airbnb.com/rooms/602842954033417083
73474  1284328048164107983  https://www.airbnb.com/rooms/1284328048164107983
55738             53770913             https://www.airbnb.com/rooms/53770913
65553  1049214057769175287  https://www.airbnb.com/rooms/1049214057769175287
...                    ...                                               ...
82970  1451839101373030611  https://www.airbnb.com/rooms/1451839101373030611
60206   794166420383829714   https://www.airbnb.com/rooms/794166420383829714
53863             46564416             https://www.airbnb.com/rooms/46564416
43309   826655969736870764   https://www.airbnb.com/rooms/826655969736870764
53005             42224040             https://www.airbnb.com/rooms/42224040

          scrape_id last_scraped  \
54849  2.025093e+13   2025-09-26
56855  2.025093e+13   2025-09-27
73474  2.025093e+13   2025-09-27
55738  2.025093e+13   2025-09-27
65553  2.025093e+13   2025-09-27
...             ...          ...
82970  2.025093e+13   2025-09-27
60206  2.025093e+13   2025-09-27
53863  2.025093e+13   2025-09-27
43309  2.025093e+13   2025-09-26
53005  2.025093e+13   2025-09-27

                                                    name  \
54849                                RIO HOTEL RESIDENCE
56855      3DF: APT FOR 4 GUESTS - DOMINGOS FERREIRA ST.
73474                     UMA CASA NO CORAÇÃO DE IPANEMA
55738                     APARTMENT IN THE CENTER OF RIO
65553                       ALUGUEL OU TEMPORADA NA URCA
...                                                  ...
82970  COPACABANA CENTRAL _8 (MINI-QUARTO 200 M DA PR...
60206     APT MODERNO E COMPLETO - PRAIA BARRA DA TIJUCA
53863     CASA ACONCHEGANTE COM VISTA PARA PÃO DE AÇÚCAR
43309               BARRA OLÍMPICA 4,  RIOCENTRO, PRAIAS
53005      RIOU016 MODERNO APT 2QT FRENTE MAR COPACABANA

                                             description host_since  \
54849                                                NaN 2016-01-30
56855  👋 ONE BLOCK FROM THE BEACH, ON RUA DOMINGOS FE... 2019-07-09
73474  THE VACATION YOU DESERVE! THE APARTMENT THAT S... 2017-01-31
55738  COZY APARTMENT IN THE HEART OF THE LAPA NEIGHB... 2021-11-16
65553  A VILLA IN URCA IS A VILLA FOR VILLA/SEASON.<B... 2021-08-14
...                                                  ...        ...
82970  PRIVATE MINI-ROOM IN SHARED APARTMENT 🧑‍🤝‍🧑<BR... 2017-02-17
60206  WELCOME!<BR /><BR />WE WILL BE HAPPY TO WELCOM... 2018-09-06
53863  HOUSE WITH A LIST VIEW OF SUGAR LOAF AND GUANA... 2014-04-05
43309  YOU WILL HAVE A GREAT TIME IN THIS COMFORTABLE... 2019-11-14
53005                                                NaN 2014-04-15

      neighbourhood_cleansed   latitude  longitude        room_type  \
54849        BARRA DA TIJUCA -23.010610 -43.344470  Entire home/apt
56855             COPACABANA -22.973036 -43.186057  Entire home/apt
73474                IPANEMA -22.984520 -43.201030  Entire home/apt
55738                 CENTRO -22.912950 -43.181260  Entire home/apt
65553                   URCA -22.954104 -43.168059  Entire home/apt
...                      ...        ...        ...              ...
82970             COPACABANA -22.968100 -43.183410     Private room
60206        BARRA DA TIJUCA -23.009230 -43.364940  Entire home/apt
53863           SANTA TERESA -22.921460 -43.183240  Entire home/apt
43309            JACAREPAGUÁ -22.963309 -43.400948  Entire home/apt
53005             COPACABANA -22.975690 -43.189100  Entire home/apt

       accommodates  bathrooms  bedrooms  beds   price  review_scores_rating  \
54849           4.0        2.0       2.0   2.0   450.0                  4.86
56855           4.0        2.0       1.0   2.0  1084.0                  5.00
73474           6.0        3.0       3.0   3.0  3040.0                  5.00
55738           5.0        1.0       1.0   2.0   184.0                  4.81
65553           2.0        1.0       1.0   0.0   315.0                  4.73
...             ...        ...       ...   ...     ...                   ...
82970           2.0        1.0       1.0   1.0    96.0                  4.50
60206           3.0        1.0       1.0   2.0   505.0                  5.00
53863           3.0        1.0       1.0   2.0   364.0                  5.00
43309           3.0        1.0       1.0   1.0   199.0                  4.84
53005           4.0        2.0       2.0   3.0   890.0                  4.88

       review_scores_accuracy  rating_vs_accuracy
54849                    5.00               False
56855                    5.00                True
73474                    5.00                True
55738                    4.88               False
65553                    4.93               False
...                       ...                 ...
82970                    4.40               False
60206                    5.00                True
53863                    4.88               False
43309                    4.89               False
53005                    4.88                True

[2327 rows x 19 columns]

In [25]:
#Salvar csv para posteridade
dados_limpos.to_csv("dados_limpos.csv", index=False)